### ISSUE TITLE
slope heterogeneity test

### ISSUE THREAD

**Issue by asifalig71** [aptech/tspdlib#3]
looking for the Gauss codes for conducting slope heterogeneity test conducted by Pesaran and Yamagata(2008)

**Comment by ec78** [comment]
Hello @asifalig71 ,

The slope heterogeneity test is not included in the **tspdlib** library. However, you can directly download the author's code for these tests from [here](http://www.econ.cam.ac.uk/people-files/emeritus/mhp1/ppfiles/Deltatest.zip). 

Erica
