### ISSUE TITLE
Bug in "coint_maki.src" file

### ISSUE THREAD

**Issue by cengiza** [aptech/tspdlib#4]
I am using tspdlib_1.1.1 and Gauss 19.2

When I run coint_maki.e example file I am getting error  "G0025 : Undefined symbol: 'tp' [coint_maki.src, line 36]"

![1](https://user-images.githubusercontent.com/1962954/102818570-f2328880-43e2-11eb-889d-e6f150dfe613.JPG)

I noticed that in coint_maki.src, line 36   "tp" variable is not defined.

![2](https://user-images.githubusercontent.com/1962954/102818663-2ad26200-43e3-11eb-96f3-599d666f8b8e.JPG)

I added these lines in coint_maki.src and example file worked.
    
**local tp; // tp-> need to define
tp = trimm; // send trim value trimm to tp**
 

![4](https://user-images.githubusercontent.com/1962954/102818828-76850b80-43e3-11eb-9efc-5f8ed98b2104.JPG)

**Comment by ec78** [comment]
@cengiza  thank you for pointing this out. We will update the .src file and will include the bug fix in our next release. This should be available shortly after the new year.

**Comment by cengiza** [comment]
You're welcome @ec78 .
